#!/usr/bin/env python3
"""Bake the input prompt glyphs in assets/input-prompts into code/padglyphdata.h.

Each PNG is resampled to GLYPH_SIZE square and written as RGBA bytes. The
engine samples the arrays down to the size a screen asks for.
"""

from pathlib import Path

from PIL import Image

GLYPH_SIZE = 32
STYLES = ["xbox", "playstation", "deck"]
BUTTONS = ["accept", "back", "third", "fourth", "menu"]

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets" / "input-prompts"
TARGET = ROOT / "code" / "padglyphdata.h"


def main() -> None:
    lines = [
        "/*******************************************************************************",
        " *                                O P E N  T S",
        " *******************************************************************************",
        " * SPDX-License-Identifier: GPL-3.0-or-later",
        " * Copyright 2026 OpenTS contributors",
        " *",
        " * See LICENSE.md for applicable additional terms and warranty disclaimers.",
        " ******************************************************************************/",
        "",
        "/* Generated by tools/padglyphs.py from assets/input-prompts. Edits are overwritten. */",
        "",
        "#pragma once",
        "",
        f"enum {{ PAD_GLYPH_SOURCE_SIZE = {GLYPH_SIZE} }};",
        "",
        "// RGBA rows, PAD_GLYPH_SOURCE_SIZE square, indexed by style then button.",
        f"static unsigned char const PadGlyphPixels[{len(STYLES)}][{len(BUTTONS)}][PAD_GLYPH_SOURCE_SIZE * PAD_GLYPH_SOURCE_SIZE * 4] = {{",
    ]
    for style in STYLES:
        lines.append("\t{")
        for button in BUTTONS:
            image = Image.open(SOURCE / f"{style}_{button}.png").convert("RGBA")
            image = image.resize((GLYPH_SIZE, GLYPH_SIZE), Image.LANCZOS)
            data = image.tobytes()
            lines.append(f"\t\t{{ // {style} {button}")
            for offset in range(0, len(data), 32):
                chunk = ",".join(str(byte) for byte in data[offset:offset + 32])
                lines.append(f"\t\t\t{chunk},")
            lines.append("\t\t},")
        lines.append("\t},")
    lines.append("};")
    lines.append("")
    TARGET.write_text("\n".join(lines))
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
