#!/usr/bin/env python3
"""Bake the sidebar section shadows in assets/sidebar-shadows into code/sidebarshadowdata.h.

Each PNG is a black silhouette on transparency, resampled to SHADOW_SIZE square
and written as RGBA bytes. A section with no PNG bakes as fully transparent and
is marked absent so the engine draws nothing for it.
"""

from pathlib import Path

from PIL import Image

SHADOW_SIZE = 64
SECTIONS = [
    "gdi_structures", "nod_structures",
    "gdi_infantry", "nod_infantry",
    "gdi_vehicles", "nod_vehicles",
    "gdi_aircraft", "nod_aircraft",
]

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets" / "sidebar-shadows"
TARGET = ROOT / "code" / "sidebarshadowdata.h"


def main() -> None:
    lines = [
        "/*******************************************************************************",
        " *                                O P E N  T S",
        " *******************************************************************************",
        " * SPDX-License-Identifier: GPL-3.0-or-later",
        " * Copyright 2026 OpenTS contributors",
        " *",
        " * See LICENSE.md for applicable additional terms and warranty disclaimers.",
        " ******************************************************************************/",
        "",
        "/* Generated by tools/sidebarshadows.py from assets/sidebar-shadows. Edits are overwritten. */",
        "",
        "#pragma once",
        "",
        f"enum {{ SIDEBAR_SHADOW_SIZE = {SHADOW_SIZE}, SIDEBAR_SHADOW_COUNT = {len(SECTIONS)} }};",
        "",
        "// Indexed by section row times two plus column side, GDI first.",
        "static bool const SidebarShadowPresent[SIDEBAR_SHADOW_COUNT] = {",
    ]
    present = [(SOURCE / f"{name}.png").exists() for name in SECTIONS]
    lines.append("\t" + ", ".join("true" if p else "false" for p in present) + ",")
    lines.append("};")
    lines.append("")
    lines.append("// RGBA rows, SIDEBAR_SHADOW_SIZE square.")
    lines.append(f"static unsigned char const SidebarShadowPixels[SIDEBAR_SHADOW_COUNT][SIDEBAR_SHADOW_SIZE * SIDEBAR_SHADOW_SIZE * 4] = {{")
    for name, exists in zip(SECTIONS, present):
        if exists:
            image = Image.open(SOURCE / f"{name}.png").convert("RGBA")
            image = image.resize((SHADOW_SIZE, SHADOW_SIZE), Image.LANCZOS)
        else:
            image = Image.new("RGBA", (SHADOW_SIZE, SHADOW_SIZE), (0, 0, 0, 0))
        data = image.tobytes()
        lines.append(f"\t{{ // {name}")
        for offset in range(0, len(data), 32):
            chunk = ",".join(str(byte) for byte in data[offset:offset + 32])
            lines.append(f"\t\t{chunk},")
        lines.append("\t},")
    lines.append("};")
    lines.append("")
    TARGET.write_text("\n".join(lines))
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
